name: Publish to NuGet

on:
  release:
    types:
      - released

jobs:
  publish-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Publish Packages
        uses: SharpAttributeParser/actions/dotnet/nuget/release-to-nuget@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nuget-token: ${{ secrets.NUGET_API_KEY }}